import uuid from "uuid/v1";

export default [
  {
    id: 1,
    name: "HR Manger",
    type: " ",
    status: "50",
    department: "12",
    title: "Link",
    section: "20",
  },
  {
    id: 2,
    name: "HR Service",
    type: " ",
    status: "50",
    department: "12",
    title: "Link",
    section: "20",
  },
  {
    id: 3,
    name: "HR Bizpartner",
    type: " ",
    status: "48",
    department: "24",
    title: "Link",
    section: "36",
  },
  {
    id: 4,
    name: "Fullstack Developer",
    type: " ",
    status: "25",
    department: "35",
    title: "Link",
    section: "34",
  },
  {
    id: 5,
    name: "Frontend Developer",
    type: " ",
    status: "50",
    department: "84",
    title: "Link",
    section: "45",
  },
  {
    id: 6,
    name: "Backend Developer",
    type: " ",
    status: "50",
    department: "65",
    title: "Link",
    section: "54",
  },
  {
    id: 7,
    name: "Project Manger",
    type: " ",
    status: "14",
    department: "13",
    title: "Link",
    section: "12",
  },
  {
    id: 8,
    name: "Business Analyst",
    type: " ",
    status: "45",
    department: "63",
    title: "Link",
    section: "44",
  },
  {
    id: 9,
    name: "Tester",
    type: " ",
    status: "32",
    department: "45",
    title: "Link",
    section: "77",
  },
  {
    id: 10,
    name: "System Analyst",
    type: " ",
    status: "42",
    department: "16",
    title: "Link",
    section: "88",
  },
];
